# Generated by Django 4.0.6 on 2022-07-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
